const list = [
  {
    id: 1,
    title: "Feijão",
    category: "básico",
    price: 0,
    img: "https://savegnagoio.vtexassets.com/arquivos/ids/354948-300-300?v=1782086778&width=300&height=300&aspect=true",
    amount: 1,
  },
  {
    id: 2,
    title: "Arroz",
    category: "básico",
    price: 0,
    img: "assets/img/arroz.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "Carne",
    category: "carne",
    price: 0,
    img: "assets/img/carne.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "Maçã",
    category: "fruta",
    price: 0,
    img: "assets/img/maca.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "Alface",
    category: "vegetal",
    price: 0,
    img: "assets/img/alface.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Frango",
    category: "carne",
    price: 0,
    img: "assets/img/frango.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Banana",
    category: "fruta",
    price: 0,
    img: "assets/img/banana.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Cenoura",
    category: "vegetal",
    price: 0,
    img: "https://savegnagoio.vtexassets.com/arquivos/ids/350693-300-300?v=1781480404&width=300&height=300&aspect=true",
    amount: 1,
  },
  {
    id: 11,
    title: "Salmão",
    category: "peixe",
    price: 0,
    img: "assets/img/salmao.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Laranja",
    category: "fruta",
    price: 0,
    img: "assets/img/laranja.jpg",
    amount: 1,
  },
  {
    id: 13,
    title: "Tomate",
    category: "vegetal",
    price: 0,
    img: "https://savegnagoio.vtexassets.com/arquivos/ids/363956-300-300?v=1781480405&width=300&height=300&aspect=true",
    amount: 1,
  },
  {
    id: 16,
    title: "Pera",
    category: "fruta",
    price: 0,
    img: "assets/img/pera.jpg",
    amount: 1,
  },
  {
    id: 17,
    title: "Brócolis",
    category: "vegetal",
    price: 0,
    img: "assets/img/brocolis.jpg",
    amount: 1,
  },
  {
    id: 19,
    title: "Peixe Dourado",
    category: "peixe",
    price: 0,
    img: "assets/img/peixe.jpg",
    amount: 1,
  },
  {
    id: 20,
    title: "Uva",
    category: "fruta",
    price: 0,
    img: "assets/img/uva.jpg",
    amount: 1,
  },
  {
    id: 21,
    title: "Espinafre",
    category: "vegetal",
    price: 0,
    img: "assets/img/espinafre.jpg",
    amount: 1,
  },
  {
    id: 24,
    title: "Manga",
    category: "fruta",
    price: 0,
    img: "assets/img/manga.jpg",
    amount: 1,
  },
  {
    id: 25,
    title: "Batata",
    category: "vegetal",
    price: 0,
    img: "https://savegnagoio.vtexassets.com/arquivos/ids/366160-300-300?v=1781480640&width=300&height=300&aspect=true",
    amount: 1,
  },
  {
    id: 28,
    title: "Abacaxi",
    category: "fruta",
    price: 0,
    img: "assets/img/abacaxi.jpg",
    amount: 1,
  },
  {
    id: 29,
    title: "Couve",
    category: "vegetal",
    price: 0,
    img: "assets/img/couve.jpg",
    amount: 1,
  },
  {
    id: 32,
    title: "Melancia",
    category: "fruta",
    price: 0,
    img: "assets/img/melancia.jpg",
    amount: 1,
  },
  {
    id: 33,
    title: "Pimentão",
    category: "vegetal",
    price: 0,
    img: "assets/img/pimentao.jpg",
    amount: 1,
  },
  {
    id: 36,
    title: "Kiwi",
    category: "fruta",
    price: 0,
    img: "assets/img/kiwi.jpg",
    amount: 1,
  },
  {
    id: 37,
    title: "Cebola",
    category: "vegetal",
    price: 0,
    img: "https://savegnagoio.vtexassets.com/arquivos/ids/372022-300-300?v=1781480471&width=300&height=300&aspect=true",
    amount: 1,
  },
  {
    id: 40,
    title: "Mamão",
    category: "fruta",
    price: 0,
    img: "assets/img/mamao.jpg",
    amount: 1,
  },
  {
    id: 44,
    title: "Morango",
    category: "fruta",
    price: 0,
    img: "assets/img/morango.jpg",
    amount: 1,
  },
  {
    id: 45,
    title: "Abóbora",
    category: "vegetal",
    price: 0,
    img: "assets/img/abobora.jpg",
    amount: 1,
  },
];

export default list;
